# Generated by Django 4.2.2 on 2023-07-03 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statline',
            options={'verbose_name_plural': 'Stat Lines'},
        ),
        migrations.AlterModelTable(
            name='statline',
            table='score_table',
        ),
    ]
