# Generated by Django 4.2.2 on 2023-07-03 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_statline_options_alter_statline_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statline',
            options={'managed': False},
        ),
    ]
