# Generated by Django 4.2.2 on 2023-07-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_statline_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('player_id', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
            ],
            options={
                'db_table': 'score_table',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='StatLine',
        ),
    ]
